# Numpy Tutorials

In [1]:
 # initially lets import numpy
    

In [2]:
 import numpy as np

In [3]:
my_lst=[1,2,3,4,5]

In [4]:
arr=np.array(my_lst)

In [5]:
 type(arr)

numpy.ndarray

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
arr.shape

(5,)

In [8]:
type(arr)

numpy.ndarray

In [9]:
## Multidimensinsional arry

In [11]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [12]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [13]:
arr.shape

(3, 5)

In [16]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [17]:
## check shape of array

In [18]:
arr.shape

(3, 5)

In [19]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

# indexing in numpy 

In [20]:
 ## accesing the array elements

In [23]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [24]:
arr[3]

4

In [25]:
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr[::]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
 ## some condition very useful in  exploratory Data Analysis

In [32]:
val=2
arr

array([ True, False, False, False, False, False, False, False, False])

In [33]:
## create array and reshape

In [34]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [36]:
arr1=np.arange(0,10).reshape(2,5)

In [37]:
arr2=np.arange(0,10).reshape(2,5)

In [38]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [39]:
np.ones(4)

array([1., 1., 1., 1.])

In [40]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
# random distribution

In [42]:
np.random.rand(3,3)

array([[0.98162628, 0.92639229, 0.99276964],
       [0.89679156, 0.82529266, 0.07963123],
       [0.84430493, 0.01585729, 0.28284847]])

In [43]:
arr_ex=np.random.randn(4,4)

In [44]:
arr_ex

array([[ 0.0850296 , -0.76712421,  2.03482595,  0.02667426],
       [ 0.67689213, -0.59805173,  0.99662197, -0.31552239],
       [ 0.31518448, -0.19572107, -2.11392274, -1.45586415],
       [ 1.22656756, -0.68151987, -0.78218359,  0.92057141]])

In [46]:
import seaborn as sns
import pandas as pd

In [ ]:
sns.displot(pd.DataFrame(arr_ex.re))